language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xuejieguo97/reatc-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xuejieguo97/reatc-test npm test -- --coverage

after_success:
  - docker build -t xuejieguo97/multi-client ./client
  - docker build -t xuejieguo97/multi-nginx ./nginx
  - docker build -t xuejieguo97/multi-server ./server
  - docker build -t xuejieguo97/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push xuejieguo97/multi-client
  - docker push xuejieguo97/multi-nginx
  - docker push xuejieguo97/multi-server
  - docker push xuejieguo97/multi-worker
  